baseURL = "http://example.org/"
languageCode = "en-us"
title = "Paul Charlesworth"

[permalinks]
blog = "/:filename/"

[taxonomies]
category = "categories"
tag = "tags"

[params]
homeText = "You just made a Hugo blog from scratch."
